# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
