# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import todo.models.helper


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='list',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=todo.models.helper.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='project',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
