# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170910_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='list',
        ),
        migrations.AddField(
            model_name='code',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Project'),
        ),
    ]
